version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - ls -a
      - echo "Installing dependencies"
      - mvn clean install -DskipTests
  build:
    commands:
      - ls -a
      - echo "Building the application"
      - mvn package -DskipTests
      - ls -a
      - cd target
      - ls -a
      
      
      
